### PR TITLE
add suppress unchecked annotation to package helper generator

### PR DESCRIPTION
**Pull request by dbachelder**
add suppress unchecked annotation to package helper generator

### CODE REVIEW

**Comment by johncarl81** [comment]
I was thinking about this a bit, what do you think about trying to add this annotation to the actual casts?:
```java
@SupressWarnings Specific specific = (Specific) getGeneral();
```

**Comment by johncarl81** [comment]
... which may not be possible with JCodeModel.

**Comment by dbachelder** [comment]
I just want my builds to look cleaner :) however you want to get there!

**Comment by johncarl81** [comment]
Hmm, what if we added this annotation to *every* generated class?

**Comment by johncarl81** [comment]
:+1:

**Pull request merged**
