### PR TITLE
add suppress for deprecation warnings

### PR DESCRIPTION
**Pull request by dbachelder**

### CODE REVIEW

**Comment by johncarl81** [comment]
Is transfuse using depreciated methods on the Android api?

**Comment by dbachelder** [comment]
for injected drawable resources

http://developer.android.com/reference/android/content/res/Resources.html#getDrawable(int)

**Comment by johncarl81** [comment]
Ah, maybe we should move to [Context.getDrawable()](http://developer.android.com/reference/android/content/Context.html#getDrawable%28int%29) instead.

**Comment by dbachelder** [comment]
that was added in api 21

**Comment by johncarl81** [comment]
Shoot, you're correct.  I wonder if we could annotate the invocation directly:
```java
@SuppressWarnings("depreciated")
resources.getDrawable(1234);
```
That way if anything else is depreciated we would know about it.  Supressing all depreciated warnings feels a little heavy handed to me.

**Comment by dbachelder** [comment]
unfortunately annotations aren't allowed in method bodies

**Comment by johncarl81** [comment]
SuppressWarnings is, at least for local variables:
```java
@Target({TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE})
@Retention(RetentionPolicy.SOURCE)
public @interface SuppressWarnings {
```
[LOCAL_VARIABLE](http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/ElementType.html#LOCAL_VARIABLE)

**Comment by dbachelder** [comment]
That is for the variable declaration.  This would only be useful if we created a temporary variable to assign the resource to then assigned that to the property on the component delegate.

**Comment by johncarl81** [comment]
Ah, you're right... hmm, with some of the newer rules I feel like we're supporting a specific version of Android anyways.  Are you not compiling against version > 21?

**Comment by dbachelder** [comment]
We are compiling against 23. What do you think makes it specific? those new annotations I added are optional...

**Comment by johncarl81** [comment]
I'm sorry, I think I was a little quick to answer and too short.  Im thinking that we fix this issue instead of masking it with suppressing the depreciation warning.  It would be fairly easy to migrate to use Context.getDrawable() instead.  Would this work for you or is there some other issue I'm not seeing?

**Comment by dbachelder** [comment]
That won't work for people not targeting >= 21.. how about using ContextCompat? 

http://developer.android.com/reference/android/support/v4/content/ContextCompat.html

**Pull request merged**
