### PR TITLE
deal with new application attr fullBackupContent

### PR DESCRIPTION
**Pull request by dbachelder**
http://developer.android.com/preview/backup/index.html

### CODE REVIEW

**Comment by johncarl81** [comment]
Do you have a reference to the related docs for this?

**Comment by dbachelder** [comment]
oh yeah.. good idea.. http://developer.android.com/preview/backup/index.html

**Comment by johncarl81** [comment]
I so wish there was a well formed DTD or something like that for the manifest.

**Comment by dbachelder** [comment]
seriously!

**Pull request merged**
