### PR TITLE
Fixes enum array handling

### PR DESCRIPTION
**Pull request by johncarl81**

### CODE REVIEW

**Comment by johncarl81** [comment]
@dbachelder I believe this addresses https://github.com/johncarl81/transfuse/pull/212, would you mind giving it a try?

**Comment by justincpollard** [comment]
@johncarl81 I was able to build our project with this branch! Nice work :-)

**Comment by johncarl81** [comment]
Awesome, thanks for verifying.  I have one more high profile fix to make
then I'd like to make a release.

**Comment by justincpollard** [comment]
Sweet! Looking forward to it :-)

**Pull request merged**
